#!/bin/sh

xqr() {
    colo="$(xrdb -q | grep -w "color$1")"
    printf '%s' ${colo##*:}
}

silent="$(xqr 0)"
fg="$(xqr 8)"
gr="$(xqr 0)"

berryc border_width       0
berryc inner_border_width 1
berryc title_height       0
berryc edge_gap 5 5 5 5

berryc smart_place "true"
berryc edge_lock   "true"

berryc focus_color   "${fg###}"
berryc unfocus_color "${gr###}"

berryc inner_focus_color   "${fg###}"
berryc inner_unfocus_color "${gr###}"

berryc text_focus_color   "${silent###}"
berryc text_unfocus_color "${silent###}"

#berryc set_font gomedium-11
berryc set_font terminus-30
pkill polybar ; polybar 1
